name: to_do_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  flutter_lints: ^2.0.0
  table_calendar: ^3.0.7
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.2.0+2
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  intl: ^0.17.0
  easy_localization: ^3.0.1
flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/translation/
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:


